name: Deploy to Droplet

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: droplet

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
        
      - name: Deploy using SSH pass
        run: | 
         sshpass -p "${{ secrets.DROPLETPASS }}" ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.DROPLETIP }} << EOF
            cd /app
            git pull origin main
            npm install
            npm run dev
          EOF
      
      
