name: Deploy to Droplet

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
        
      - name: Deploy using SSH pass
        run: | 
         sshpass -p "${{ secrets.dropletPass }}" ssh -o StrictHostKeyChecking=no ${{ secrets.dropletUser }}@your.droplet.ip << 'EOF'
            cd /app
            git pull origin main
            npm install
            npm run dev
          EOF
      
      
